apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  source:
    chart: keycloak
    repoURL: https://github.com/bitnami/charts.git
    path: bitnami/keycloak
    helm:
      releaseName: keycloak
      valueFiles:
        - values/values.yaml
