apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  source:
    repoURL: https://github.com/bitnami/charts.git
    path: bitnami/keycloak
    targetRevision: HEAD
    helm:
      releaseName: keycloak
      valuesObject:
        auth:
        adminUser: admin
        adminPassword: admin

        ingress:
          enabled: true
          ingressClassName: traefik
          hostname: keycloak.thor.frec.kr

        postgresql:
          enabled: true
          auth:
            username: postgres
            password: postgres
            database: keycloak
            secretKeys:
              userPasswordKey: postgres-password
