apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: keycloak-dev
    namespace: keycloak-dev
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: keycloak
    version: 24.5.7

    valuesInline:
      auth:
        adminUser: admin
        adminPassword: admin

      ingress:
        enabled: true
        ingressClassName: traefik
        hostname: keycloak.dev.thor.frec.kr

      postgresql:
        enabled: true
        auth:
          username: postgres
          password: postgres
          database: keycloak
          secretKeys:
            userPasswordKey: postgres-password

      service:
        ports:
          http: 10080
          https: 10443

helmGlobals:
  chartHome: charts
