apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../prod

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: keycloak
    path: patch.ingress.yaml
