apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../prod

helmCharts:
  - name: keycloak
    namespace: keycloak-dev
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: keycloak
    version: 24.5.7

    valuesMerge: override
    additionalValuesFiles:
      - ./values.yaml
