apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: keycloak
    namespace: keycloak
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: keycloak
    valuesFile: ./charts/keycloak/override.values.yaml
    version: 24.5.7

helmGlobals:
  chartHome: charts
