apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: keycloak
    namespace: keycloak-dev
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: keycloak
    version: 24.5.7

    valuesInline:
      auth:
        adminUser: admin
        adminPassword: admin

      ingress:
        enabled: true
        ingressClassName: traefik
        hostname: dev.thor.frec.kr

      postgresql:
        enabled: true
        auth:
          username: postgres
          password: postgres
          database: keycloak
          secretKeys:
            userPasswordKey: postgres-password

helmGlobals:
  chartHome: charts
