apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: applicationset
  namespace: argocd

spec:
  generators:
    - git:
        repoURL: https://github.com/freckie/playground
        revision: main
        directories:
          - path: "250423/apps"
  
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=false
          - CreateNamespace=true
      source:
        repoURL: https://github.com/freckie/playground
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc.cluster.local
        namespace: '{{path}}'

