apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-config
  namespace: argocd
data:
  configManagementPlugins: |
    - name: kustomize-helm
      generate:
        command: [ "kubectl", "kustomize", "--enable-helm", "{{path}}" ]