apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  configManagementPlugins: |
    - name: kustomize-helm
      generate:
        command: [ "kustomize", "build", "--enable-helm", "{{path}}" ]