apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: "27.15.0"
      helm:
        valueFiles:
          - $appRepo/250424/apps/observability/base/values.yaml
    - repoURL: https://github.com/freckie/playground
      targetRevision: master
      ref: appRepo