server:
  extraFlags:
    - web.enable-remote-write-receiver
    - web.enable-lifecycle

alertmanager:
  enabled: false

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - 192.168.0.52
    - thor.frec.kr