apiVersion: v1
kind: Namespace
metadata:
  name: keycloak-dev
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  destination:
    namespace: keycloak-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: keycloak
    helm:
      releaseName: keycloak
      valueFiles:
      - values/override.values.yaml
    path: bitnami/keycloak
    repoURL: https://github.com/bitnami/charts.git
    targetRevision: main
