apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authz
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: authz
  source:
    repoURL: https://openfga.github.io/helm-charts
    chart: openfga
    targetRevision: "0.2.29"
    helm:
      releaseName: openfga
      values: |
        replicaCount: 1
        datastore:
          engine: postgres
          uri: "postgres://postgres:postgres@openfga-postgresql.authz.svc.cluster.local:5432/postgres?sslmode=disable"
        postgresql:
          enabled: true
          auth:
            username: postgres
            password: postgres
            database: postgres
            secretKeys:
              userPasswordKey: openfga-password
