auth:
  adminUser: admin
  adminPassword: admin

ingress:
  enabled: true
  ingressClassName: traefik
  hostname: dev.thor.frec.kr

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: keycloak
