auth:
  adminUser: admin
  adminPassword: admin
  existingSecret: keycloak-secret
  passwordSecretKey: ADMIN_PASSWORD

ingress:
  enabled: true
  ingressClassName: traefik
  hostname: dev.thor.frec.kr

postgresql:
  enabled: true
  auth:
    username: postgres
    database: keycloak
    existingSecret: keycloak-secret
    secretKeys:
      userPasswordKey: POSTGRES_PASSWORD
